
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 39
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 105
#define YY_END_OF_BUFFER 106
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[306] =
    {   0,
        0,    0,  106,  104,  103,    1,   88,  104,  104,   94,
       87,  104,   82,   83,   92,   91,   79,   90,   86,   93,
       11,   11,   80,   76,   95,   81,   96,   99,  102,   84,
       85,   97,  102,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
       77,   98,   78,   89,   30,    0,   19,    0,    0,    0,
       35,   78,   31,   40,    0,    0,   33,   23,   36,   24,
       37,   22,   17,    2,    3,   34,   18,   11,    0,   14,
        0,   85,   77,   84,   25,   27,   29,   28,   26,    0,
      102,   41,  102,  102,  102,  102,  102,  102,  102,   50,

      102,  102,  102,  102,  102,  102,   58,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
      102,   42,   32,    0,    0,   15,    0,   17,   12,    0,
       18,    0,   16,   13,   20,   38,   39,   21,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
       56,  102,   59,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
      102,    0,    0,    0,   17,    0,   17,    0,   18,   16,
       13,  102,   43,  102,   45,   46,  102,  102,  102,  102,
       52,   53,  102,  102,   57,   60,  101,  102,  102,  102,

      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
       72,  102,  102,    0,    0,    0,   17,  102,   44,   47,
      102,  102,  102,  102,   55,  102,  102,  102,  100,   63,
      102,  102,  102,  102,  102,  102,   70,  102,  102,   74,
        0,    0,  102,  102,  102,   51,   54,  102,   62,   64,
       65,   66,   67,   68,  102,  102,  102,    0,    0,  102,
      102,   49,  102,   69,  102,  102,    0,    0,  102,   48,
       61,   71,   73,    0,    0,    0,    0,  102,    0,    0,
        0,    0,    0,    0,    0,    0,   75,    8,   10,    0,
        0,    0,    0,    0,    0,    0,   10,    0,    0,    7,

        4,    9,    6,    5,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   27,   27,   27,   28,   29,
       30,   30,   30,   30,   30,   31,   30,   30,   30,   30,
       30,   30,   30,   30,   32,   30,   30,   33,   30,   30,
       34,   35,   36,   37,   38,    1,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   30,   48,   49,   50,   51,
       52,   53,   30,   54,   55,   56,   57,   58,   59,   60,
       61,   62,   63,   64,   65,   66,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[67] =
    {   0,
        1,    1,    1,    2,    1,    3,    1,    1,    1,    4,
        1,    1,    1,    1,    1,    1,    5,    1,    6,    6,
        1,    1,    1,    1,    1,    1,    7,    7,    7,    8,
        8,    8,    8,    1,    1,    1,    1,    8,    7,    7,
        7,    7,    7,    7,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[318] =
    {   0,
        0,    0,  627,  628,  628,  628,  602,   61,   26,   45,
       62,  590,  628,  628,  600,   58,  628,   59,   57,   61,
       80,   61,  598,  628,   82,  598,   63,  628,  615,  628,
      628,  596,   88,   85,   89,   92,   96,  101,  108,   95,
      111,  113,  110,  109,  103,  126,  114,  115,  116,  118,
      628,  106,  628,  628,  628,  119,  628,  616,  575,  566,
      628,  628,  628,  628,  118,  124,  628,  628,  628,  628,
      628,  628,  158,  628,  628,  628,  175,  180,  160,  160,
        0,  628,  628,  628,  112,  628,  628,  628,  134,  163,
      610,  628,  139,  127,  145,  135,  175,  165,  187,  190,

      150,  204,  207,  214,  215,  209,  609,  216,  219,  220,
      221,  226,  234,  222,  230,  237,  232,  224,  233,  236,
      239,  628,  628,  570,  572,  628,  230,  628,  270,  237,
      628,  214,  274,  275,  628,  628,  628,  628,  229,  235,
      242,  252,  246,  253,  258,  256,  278,  254,  296,  304,
      606,  305,  605,  306,  309,  310,  311,  314,  316,  319,
      321,  320,  322,  323,  325,  327,  324,  328,  332,  329,
      330,  563,  560,  235,  333,  326,  628,  328,  364,  628,
      354,  335,  602,  343,  601,  600,  338,  349,  331,  348,
      599,  598,  344,  350,  597,  596,  595,  353,  359,  363,

      360,  383,  384,  386,  393,  394,  395,  399,  396,  401,
      594,  404,  406,  548,  541,  396,  399,  414,  591,  590,
      415,  416,  418,  417,  589,  419,  420,  423,  588,  587,
      425,  426,  428,  427,  431,  436,  586,  438,  439,  585,
      547,  547,  445,  444,  446,  582,  581,  447,  580,  579,
      578,  577,  576,  575,  449,  451,  450,  576,  536,  456,
      452,  572,  453,  571,  458,  465,    0,  469,  466,  570,
      569,  568,  567,  568,  474,  554,  553,  472,  462,  560,
      543,  536,  503,  527,  497,  525,  527,  468,    0,  486,
      509,  463,  489,  497,  473,  492,    0,  490,  466,  628,

      628,  494,  628,  628,  628,  514,  522,  528,  531,  532,
      539,  543,  547,  550,  554,  558,  561
    } ;

static yyconst flex_int16_t yy_def[318] =
    {   0,
      305,    1,  305,  305,  305,  305,  305,  306,  305,  305,
      305,  307,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  308,  305,
      305,  305,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      305,  305,  305,  305,  305,  306,  305,  306,  305,  305,
      305,  305,  305,  305,  307,  307,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      309,  305,  305,  305,  305,  305,  305,  305,  305,  306,
      308,  305,  308,  308,  308,  308,  308,  308,  308,  308,

      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  309,  305,  305,  305,  305,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,

      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  305,  305,  305,  305,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      305,  305,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  305,  305,  308,
      308,  308,  308,  308,  308,  308,  310,  305,  308,  308,
      308,  308,  308,  311,  305,  312,  313,  308,  314,  311,
      315,  316,  305,  312,  305,  313,  308,  305,  317,  305,
      315,  305,  316,  305,  305,  305,  317,  305,  305,  305,

      305,  305,  305,  305,    0,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305
    } ;

static yyconst flex_int16_t yy_nxt[695] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   29,   29,   29,
       29,   29,   29,   30,    4,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   40,   29,   41,   29,   42,   43,
       29,   29,   44,   45,   46,   47,   48,   49,   50,   29,
       29,   29,   51,   52,   53,   54,   57,   59,   61,   62,
       63,   68,   60,   74,   70,   73,   73,   77,   75,   78,
       78,   69,   71,   72,   76,   64,   88,   89,   79,   83,
       90,   80,   80,   90,   90,   58,   77,   90,   78,   78,

       90,   90,   84,   79,   85,   86,   90,   79,   90,   80,
       80,   80,   81,   90,   90,   90,   90,   80,   90,   90,
       90,   90,   79,   90,   57,   93,  305,  126,   80,  122,
       96,   90,  305,   65,  135,  136,   80,   97,   99,   81,
      305,   94,   95,   98,  305,  112,  106,  100,  110,  101,
      305,  102,   66,   58,  107,  305,  104,  137,  138,  105,
      103,  108,  111,  121,  109,  119,  113,  120,   57,  123,
      305,  114,  115,  132,  118,  132,   73,   73,  133,  133,
      305,  116,  140,  139,  117,  127,  128,  141,  128,  142,
       80,   80,  305,  129,  129,  305,   77,   58,   78,   78,

      127,  128,  130,  131,  147,  131,  128,   79,   80,  305,
       80,   80,  305,  143,  305,  144,   80,  130,  131,  305,
      305,  305,   79,  131,  305,  305,  305,  305,   80,  305,
      145,  305,  133,  133,  305,  305,   80,  305,  305,  305,
      305,  305,  305,  174,  305,  174,  146,  305,  175,  175,
      178,  305,  178,  175,  175,  179,  179,  305,  305,  305,
      148,  305,  149,  305,  152,  150,  155,  156,  151,  154,
      157,  153,  159,  160,  161,  163,  166,  182,  165,  167,
      184,  158,  169,  305,  170,  171,  183,  168,  129,  129,
      164,  162,  133,  133,  185,  190,  189,  176,  177,  186,

      177,  305,  180,  192,  180,  181,  181,  187,  188,  305,
      305,  305,  176,  177,  305,  305,  305,  180,  177,  305,
      191,  305,  180,  181,  305,  305,  305,  305,  305,  305,
      305,  181,  305,  305,  305,  305,  305,  305,  193,  216,
      305,  216,  194,  305,  217,  217,  179,  179,  305,  305,
      196,  175,  175,  305,  305,  305,  195,  199,  305,  197,
      198,  128,  204,  128,  305,  305,  201,  212,  305,  208,
      200,  203,  202,  211,  210,  209,  128,  205,  213,  206,
      207,  128,  179,  179,  181,  181,  218,  222,  305,  305,
      219,  305,  131,  220,  131,  221,  223,  224,  305,  305,

      305,  305,  181,  229,  305,  225,  305,  131,  226,  305,
      181,  305,  131,  227,  217,  217,  228,  217,  217,  305,
      305,  305,  305,  305,  305,  305,  231,  177,  305,  177,
      305,  305,  305,  305,  234,  235,  305,  232,  230,  233,
      236,  305,  177,  305,  305,  238,  237,  177,  240,  305,
      305,  305,  305,  243,  305,  305,  305,  305,  305,  239,
      246,  305,  229,  305,  245,  244,  250,  247,  252,  251,
      305,  305,  275,  249,  276,  248,  254,  305,  255,  281,
      288,  288,  253,  260,  296,  257,  288,  288,  256,  263,
      304,  277,  264,  265,  270,  303,  282,  301,  266,  272,

      261,  262,  300,  278,  269,  292,  271,  273,  299,  287,
      302,  302,  302,  302,   56,   56,   56,   56,   56,   56,
       56,   56,   65,   65,   65,  290,   65,   65,   65,   65,
       91,  298,  305,   91,   91,   91,  134,  134,  274,  274,
      280,  285,  295,  283,  280,  280,  280,  284,  294,  284,
      284,  286,  292,  286,  286,  289,  289,  289,  291,  290,
      291,  291,  293,  279,  293,  293,  297,  297,  297,  285,
      283,  279,  305,  305,  305,  305,  305,  305,  268,  267,
      305,  305,  305,  305,  305,  305,  305,  305,  259,  258,
      305,  305,  305,  305,  305,  305,  305,  242,  241,  305,

      305,  305,  305,  305,  305,  305,  305,  305,  215,  214,
      305,  305,  173,  172,  305,  305,  125,  124,  305,   92,
       90,   87,   82,   67,   66,   55,  305,    3,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305

    } ;

static yyconst flex_int16_t yy_chk[695] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    8,    9,   10,   10,
       11,   16,    9,   20,   18,   19,   19,   22,   20,   22,
       22,   16,   18,   18,   20,   11,   27,   27,   22,   25,
       34,   22,   22,   33,   35,    8,   21,   36,   21,   21,

       40,   37,   25,   22,   25,   25,   38,   21,   45,   22,
       21,   21,   21,   39,   44,   43,   41,   22,   42,   47,
       48,   49,   21,   50,   56,   33,   66,   65,   21,   52,
       36,   46,   94,   66,   85,   85,   21,   36,   37,   21,
       96,   34,   35,   36,   93,   45,   40,   37,   43,   38,
       95,   38,   65,   56,   41,  101,   39,   89,   89,   39,
       38,   41,   44,   50,   42,   48,   46,   49,   90,   52,
       98,   46,   46,   79,   47,   79,   73,   73,   79,   79,
       97,   46,   94,   93,   46,   73,   73,   95,   73,   96,
       80,   80,   99,   77,   77,  100,   78,   90,   78,   78,

       73,   73,   77,   77,  101,   77,   73,   78,   80,  102,
       78,   78,  103,   97,  106,   98,   80,   77,   77,  104,
      105,  108,   78,   77,  109,  110,  111,  114,   78,  118,
       99,  112,  132,  132,  139,  115,   78,  117,  119,  113,
      140,  120,  116,  127,  121,  127,  100,  141,  127,  127,
      130,  143,  130,  174,  174,  130,  130,  142,  144,  148,
      102,  146,  103,  145,  106,  104,  110,  111,  105,  109,
      112,  108,  113,  114,  115,  116,  118,  139,  117,  119,
      141,  112,  120,  147,  120,  121,  140,  119,  129,  129,
      116,  115,  133,  133,  142,  146,  145,  129,  129,  143,

      129,  149,  133,  148,  133,  134,  134,  144,  144,  150,
      152,  154,  129,  129,  155,  156,  157,  133,  129,  158,
      147,  159,  133,  134,  160,  162,  161,  163,  164,  167,
      165,  134,  166,  168,  170,  171,  189,  169,  149,  176,
      182,  176,  150,  187,  176,  176,  178,  178,  184,  193,
      154,  175,  175,  190,  188,  194,  152,  157,  198,  155,
      156,  175,  162,  175,  199,  201,  159,  170,  200,  166,
      158,  161,  160,  169,  168,  167,  175,  163,  171,  164,
      165,  175,  179,  179,  181,  181,  182,  189,  202,  203,
      184,  204,  179,  187,  179,  188,  190,  193,  205,  206,

      207,  209,  181,  201,  208,  194,  210,  179,  198,  212,
      181,  213,  179,  199,  216,  216,  200,  217,  217,  218,
      221,  222,  224,  223,  226,  227,  203,  217,  228,  217,
      231,  232,  234,  233,  206,  207,  235,  204,  202,  205,
      208,  236,  217,  238,  239,  210,  209,  217,  213,  244,
      243,  245,  248,  218,  255,  257,  256,  261,  263,  212,
      223,  260,  226,  265,  222,  221,  231,  224,  233,  232,
      266,  269,  268,  228,  268,  227,  235,  278,  236,  275,
      279,  279,  234,  243,  288,  239,  288,  288,  238,  248,
      299,  268,  255,  256,  261,  298,  275,  295,  257,  265,

      244,  245,  294,  269,  260,  293,  263,  266,  292,  278,
      296,  296,  302,  302,  306,  306,  306,  306,  306,  306,
      306,  306,  307,  307,  307,  291,  307,  307,  307,  307,
      308,  290,  287,  308,  308,  308,  309,  309,  310,  310,
      311,  286,  285,  284,  311,  311,  311,  312,  283,  312,
      312,  313,  282,  313,  313,  314,  314,  314,  315,  281,
      315,  315,  316,  280,  316,  316,  317,  317,  317,  277,
      276,  274,  273,  272,  271,  270,  264,  262,  259,  258,
      254,  253,  252,  251,  250,  249,  247,  246,  242,  241,
      240,  237,  230,  229,  225,  220,  219,  215,  214,  211,

      197,  196,  195,  192,  191,  186,  185,  183,  173,  172,
      153,  151,  125,  124,  107,   91,   60,   59,   58,   32,
       29,   26,   23,   15,   12,    7,    3,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "file.l"
#line 11 "file.l"
//int yylineno = 1;
char datatype[100] = "dummy";
int tl;
char next;
#include <stdio.h>
#include <string.h> 
#line 725 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 19 "file.l"

#line 941 "lex.yy.c"

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 306 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 628 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 20 "file.l"
{ yylineno++; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 21 "file.l"
{ multicomment(); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 22 "file.l"
{ singlecomment();yylineno++; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 24 "file.l"
{}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 25 "file.l"
{}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 26 "file.l"
{}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 27 "file.l"
{}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 29 "file.l"
{ return DEFINE;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 30 "file.l"
{ return DEFINE;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 31 "file.l"
{ return DEFINE;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 33 "file.l"
{   return CONSTANT; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 34 "file.l"
{	 return CONSTANT; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 35 "file.l"
{   return CONSTANT; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 36 "file.l"
{   return CONSTANT; }
	YY_BREAK
case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
#line 37 "file.l"
{   return CONSTANT; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 38 "file.l"
{   return CONSTANT; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 39 "file.l"
{   return CONSTANT; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 40 "file.l"
{   return CONSTANT; }
	YY_BREAK
case 19:
/* rule 19 can match eol */
YY_RULE_SETUP
#line 42 "file.l"
{   return STRING_LITERAL; } 
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 45 "file.l"
{return KERNEL_OPEN;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 46 "file.l"
{return KERNEL_CLOSE;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 47 "file.l"
{  return PTR_OP; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 48 "file.l"
{  return INC_OP; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 49 "file.l"
{  return DEC_OP; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 50 "file.l"
{  return LEFT_OP; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 51 "file.l"
{  return RIGHT_OP; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 52 "file.l"
{  return LE_OP; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 53 "file.l"
{  return GE_OP; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 54 "file.l"
{  return EQ_OP; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 55 "file.l"
{  return NE_OP; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 56 "file.l"
{  return AND_OP; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 57 "file.l"
{  return OR_OP; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 58 "file.l"
{  return MUL_ASSIGN; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 59 "file.l"
{  return DIV_ASSIGN; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 60 "file.l"
{  return MOD_ASSIGN; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 61 "file.l"
{  return ADD_ASSIGN; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 62 "file.l"
{  return SUB_ASSIGN; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 63 "file.l"
{  return LEFT_ASSIGN; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 64 "file.l"
{  return RIGHT_ASSIGN; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 65 "file.l"
{  return AND_ASSIGN; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 66 "file.l"
{  return XOR_ASSIGN; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 67 "file.l"
{  return OR_ASSIGN; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 69 "file.l"
{ return AUTO; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 70 "file.l"
{ return BREAK; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 71 "file.l"
{ return CASE; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 72 "file.l"
{ return CHAR; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 73 "file.l"
{ return CONST; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 74 "file.l"
{ return CONTINUE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 75 "file.l"
{ return DEFAULT; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 76 "file.l"
{ return DO; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 77 "file.l"
{ return DOUBLE; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 78 "file.l"
{ return ELSE; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 79 "file.l"
{ return ENUM; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 80 "file.l"
{ return EXTERN; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 81 "file.l"
{  return FLOAT; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 82 "file.l"
{ return FOR; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 83 "file.l"
{ return GOTO; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 84 "file.l"
{ return IF; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 85 "file.l"
{  return INT; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 86 "file.l"
{ return LONG; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 87 "file.l"
{ return REGISTER; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 88 "file.l"
{ return RETURN; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 89 "file.l"
{ return SHORT; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 90 "file.l"
{ return SIGNED; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 91 "file.l"
{ return SIZEOF; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 92 "file.l"
{ return STATIC; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 93 "file.l"
{ return STRUCT; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 94 "file.l"
{ return SWITCH; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 95 "file.l"
{ return TYPEDEF; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 96 "file.l"
{ return UNION; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 97 "file.l"
{ return UNSIGNED; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 98 "file.l"
{ return VOID; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 99 "file.l"
{ return VOLATILE; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 100 "file.l"
{ return WHILE; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 101 "file.l"
{return GLOBAL;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 103 "file.l"
{   return(';'); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 104 "file.l"
{  return('{'); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 105 "file.l"
{  return('}'); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 106 "file.l"
{  return(','); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 107 "file.l"
{  return(':'); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 108 "file.l"
{  return('='); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 109 "file.l"
{  return('('); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 110 "file.l"
{  return(')'); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 111 "file.l"
{  return('['); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 112 "file.l"
{  return(']'); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 113 "file.l"
{  return('.'); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 114 "file.l"
{  return('&'); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 115 "file.l"
{  return('!'); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 116 "file.l"
{  return('~'); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 117 "file.l"
{  return('-'); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 118 "file.l"
{  return('+'); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 119 "file.l"
{  return('*'); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 120 "file.l"
{  return('/'); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 121 "file.l"
{  return('%'); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 122 "file.l"
{  return('<'); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 123 "file.l"
{  return('>'); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 124 "file.l"
{  return('^'); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 125 "file.l"
{  return('|'); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 126 "file.l"
{  return('?'); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 127 "file.l"
{  return IDENTIFIER; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 128 "file.l"
{  return IDENTIFIER; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 129 "file.l"
{  return IDENTIFIER;}
	YY_BREAK
case 103:
/* rule 103 can match eol */
YY_RULE_SETUP
#line 130 "file.l"
{  }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 131 "file.l"
{ /* ignore bad characters */ }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 132 "file.l"
ECHO;
	YY_BREAK
#line 1527 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 306 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 306 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 305);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 131 "file.l"



yywrap()
{
	return(1);
}
multicomment()
{
	char c, c1;
	while ((c = input()) != '*' && c != 0){
		if(c=='\n')
			yylineno++;
	};
	c1=input();
	
	if(c=='*' && c1=='/')
	{
		c=0;
	}
	if (c != 0)
		putchar(c1);
}
singlecomment()
{
	char c;
	while(c=input()!='\n');
	if(c=='\n')
		{c=0;
		yylineno++;}
	if(c!=0)
		putchar(c);
}

